[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
borsh = "0.9.3"
clap = { version = "3.1.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1.34"
tracing-subscriber = "0.2.4"

near-lake-framework = "0.4.0"
